language: cpp
script:
    - chmod a+x scripts/*
    - mkdir -p build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug ${CMAKE_OPTIONS} && cmake --build . && ctest -V
matrix:
  include:
    - os: osx
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: CMAKE_OPTIONS=-GNinja
      addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - ppa:ostogvin/tjo-develop
            packages:
              - cmake-data
              - cmake
              - ninja-build
              - libboost-all-dev
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: CMAKE_OPTIONS=-GNinja
      addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - ppa:ostogvin/tjo-develop
            packages:
              - cmake-data
              - cmake
              - ninja-build
              - libboost-all-dev
