language: cpp
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/boost-1.66.0
before_install: |
    if [[ "${BOOST_VERSION}" != "" ]]; then
      BOOST_DIR=boost-${BOOST_VERSION}
      if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
          BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
          mkdir -p ${BOOST_DIR}
          { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; }
      fi
      cd ${BOOST_DIR}
      ./bootstrap.sh --with-libraries=filesystem,program_options,system
      ./b2
      cd ..
      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
      export BOOST_ROOT=`pwd`/${BOOST_DIR}
    fi
script:
    - chmod a+x scripts/*
    - mkdir -p build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug ${CMAKE_OPTIONS} && cmake --build . && ctest -V
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
      packages:
        - cmake-data
        - cmake
        - ninja-build
        - g++-4.9
        - clang-5.0
compiler:
  - clang
  - gcc
os:
  - osx
  - linux
env:
  - BOOST_VERSION=1.66.0
